<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Dodo.Primitives" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.AI.Abstractions" Version="10.3.0" />
    <PackageReference Include="Microsoft.Extensions.VectorData.Abstractions" Version="10.0.1" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Helpdesk.Shared\Helpdesk.Shared.csproj" />
  </ItemGroup>
</Project>
