// <auto-generated />
using System;
using Helpdesk.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Helpdesk.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HelpdeskDbContext))]
    [Migration("20250812160000_AddOrgToKbAndEmbeddings")]
    partial class AddOrgToKbAndEmbeddings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Intentionally left empty. Use HelpdeskDbContextModelSnapshot for the model.
#pragma warning restore 612, 618
        }
    }
}

