// <auto-generated />
using System;
using System.Collections.Generic;
using Helpdesk.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace Helpdesk.Infrastructure.Migrations
{
    [DbContext(typeof(HelpdeskDbContext))]
    [Migration("20260310154040_AddOrganizationOrchestrationTenantLinking")]
    partial class AddOrganizationOrchestrationTenantLinking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Helpdesk.Infrastructure.Persistence.Connectivity.M2MConnectivitySettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("RemoteAudience")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("RemoteAuthority")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("RemoteBaseUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("RemoteSystemName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RemoteTokenEndpoint")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("M2MConnectivitySettings", (string)null);
                });

            modelBuilder.Entity("Helpdesk.Infrastructure.Persistence.Entities.NotificationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsGlobal")
                        .HasColumnType("boolean");

                    b.Property<string>("Link")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReadUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Reference")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("TenantId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("CreatedUtc");

                    b.HasIndex("IsGlobal");

                    b.HasIndex("Reference");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.HasIndex("Category", "CreatedUtc");

                    b.HasIndex("TenantId", "Category");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("Helpdesk.Infrastructure.Persistence.Entities.NotificationReadEntity", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("ReadUtc")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("NotificationId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("NotificationReads", (string)null);
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.ActivityLog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RelatedEntityId")
                        .HasColumnType("text");

                    b.Property<string>("TicketId")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.AiModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AiProviderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ExtraHeadersJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("AiProviderId");

                    b.ToTable("AiModels", (string)null);
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.AiProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKeyEncrypted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DefaultModel")
                        .HasColumnType("text");

                    b.Property<string>("ExtraHeadersJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("AiProviders", (string)null);
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.Asset", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("TicketId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UploadedById")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.AutomationBinding", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("LastCorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("LastReviewedDriftAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastSyncDirection")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("LastSyncHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("LastSyncVersion")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RequestFormId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("OrchestrationJobDefinitionId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("OrchestrationJobDefinitionName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("OrchestrationRequestDefinitionId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("OrchestrationRequestDefinitionName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("SyncState")
                        .HasColumnType("integer");

                    b.Property<Guid>("TaskTemplateId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "OrchestrationRequestDefinitionId");

                    b.HasIndex("OrganizationId", "RequestFormId", "TaskTemplateId")
                        .IsUnique();

                    b.ToTable("AutomationBindings", (string)null);
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.AutomationRule", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Actions")
                        .HasColumnType("text");

                    b.Property<string>("Conditions")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AutomationRules");
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.BlockedEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("BlockedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Domain")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BlockedEntities");
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.ChangeCategoryLink", b =>
                {
                    b.Property<string>("ChangeId")
                        .HasColumnType("text");

                    b.Property<Guid>("TicketCategoryId")
                        .HasColumnType("uuid");

                    b.HasKey("ChangeId", "TicketCategoryId");

                    b.HasIndex("TicketCategoryId");

                    b.ToTable("ChangeCategoryLinks", (string)null);
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.Customer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.EmailInboxSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("BackgroundSyncEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClientSecret")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("MailHost")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MailboxAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MailboxFolder")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("UseSsl")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("MailboxAddress")
                        .IsUnique();

                    b.ToTable("EmailInboxSettings");
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.EmailLayout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("HtmlContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TenantId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name", "TenantId")
                        .IsUnique();

                    b.ToTable("EmailLayouts");
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.EmailTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("HtmlContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<int?>("LayoutId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LayoutId");

                    b.ToTable("EmailTemplates");
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.ImapEmailSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BlockedFolder")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClientSecret")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastTestStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mailbox")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<string>("ProcessedFolder")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("UseSsl")
                        .HasColumnType("boolean");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ImapEmailSettings");
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.IncidentCategoryLink", b =>
                {
                    b.Property<string>("IncidentId")
                        .HasColumnType("text");

                    b.Property<Guid>("TicketCategoryId")
                        .HasColumnType("uuid");

                    b.HasKey("IncidentId", "TicketCategoryId");

                    b.HasIndex("TicketCategoryId");

                    b.ToTable("IncidentCategoryLinks", (string)null);
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.KnowledgeBaseArticle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Application")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedByModel")
                        .HasColumnType("text");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastRegeneratedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LinkedTicketId")
                        .HasColumnType("text");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Problem")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PublishedById")
                        .HasColumnType("text");

                    b.Property<string>("Resolution")
                        .HasColumnType("text");

                    b.Property<string>("RootCause")
                        .HasColumnType("text");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceIncidentId")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Draft");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("KnowledgeBaseArticles", (string)null);
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.KnowledgeBaseCategory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("KnowledgeBaseCategories");
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.KnowledgeEmbedding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChunkId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("KnowledgeBaseArticleId")
                        .HasColumnType("uuid");

                    b.Property<double>("LastScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0);

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Vector>("Vector")
                        .IsRequired()
                        .HasColumnType("vector(1536)");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgeBaseArticleId");

                    b.HasIndex("OrganizationId", "SourceType")
                        .HasDatabaseName("ix_embedding_org_source");

                    b.ToTable("KnowledgeEmbeddings", (string)null);
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.Organization", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AssignedSlaId")
                        .HasColumnType("text");

                    b.Property<string>("ContactInfo")
                        .HasColumnType("text");

                    b.Property<string>("DnsName")
                        .HasColumnType("text");

                    b.Property<bool>("EnableAiIntake")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<int?>("OrchestrationTenantId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("OrchestrationTenantLinkedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrchestrationTenantName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DnsName")
                        .IsUnique();

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.OrganizationAiKbSettings", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AllowedServicesCsv")
                        .HasColumnType("text");

                    b.Property<double>("AnswerThreshold")
                        .HasColumnType("double precision");

                    b.Property<int>("EmbeddingDimensions")
                        .HasColumnType("integer");

                    b.Property<string>("EmbeddingModel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmbeddingProviderId")
                        .HasColumnType("text");

                    b.Property<bool>("EnableAiAnswers")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnableAiSearch")
                        .HasColumnType("boolean");

                    b.Property<string>("KnowledgeModelName")
                        .HasColumnType("text");

                    b.Property<string>("KnowledgeProviderId")
                        .HasColumnType("text");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("SearchThreshold")
                        .HasColumnType("double precision");

                    b.Property<int>("SuggestionLimit")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("OrganizationAiKbSettings", (string)null);
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.RequestCategoryLink", b =>
                {
                    b.Property<string>("RequestId")
                        .HasColumnType("text");

                    b.Property<Guid>("TicketCategoryId")
                        .HasColumnType("uuid");

                    b.HasKey("RequestId", "TicketCategoryId");

                    b.HasIndex("TicketCategoryId");

                    b.ToTable("RequestCategoryLinks", (string)null);
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.RequestForm", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("AllowedOrganizationIds")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JsonSchema")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("OrganizationId")
                        .HasColumnType("text");

                    b.Property<int>("ReleaseStatus")
                        .HasColumnType("integer");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RequestForms");
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.Service", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AllowedCustomerIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AllowedOrganizationIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParentServiceId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.SlaEscalationRule", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Metric")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("PolicyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Recipients")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("RecipientsJson")
                        .HasDefaultValueSql("'[]'");

                    b.Property<string>("Targets")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("TargetsJson")
                        .HasDefaultValueSql("'[]'");

                    b.Property<int>("TriggerPercent")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PolicyId", "Metric", "TriggerPercent")
                        .IsUnique();

                    b.ToTable("SlaEscalationRules");
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.SlaPolicy", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AppliesTo")
                        .HasColumnType("integer");

                    b.Property<int?>("AutoResumeAfterHours")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MatchRank")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("ResolutionTimeHours")
                        .HasColumnType("integer");

                    b.Property<int>("ResponseTimeHours")
                        .HasColumnType("integer");

                    b.Property<int>("ScopeType")
                        .HasColumnType("integer");

                    b.Property<string>("ServiceId")
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ScopeType", "AppliesTo", "ServiceId", "Priority", "IsActive");

                    b.HasIndex("TenantId", "AppliesTo", "ServiceId", "Priority", "IsActive");

                    b.ToTable("SlaPolicies");
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.SlaReportSendEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("PeriodEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("PeriodStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("SentAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SubscriptionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId", "PeriodStartUtc", "PeriodEndUtc")
                        .IsUnique();

                    b.ToTable("SlaReportSendEvents", (string)null);
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.SlaReportSubscription", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer");

                    b.Property<bool>("IncludeCsvAttachment")
                        .HasColumnType("boolean");

                    b.Property<bool>("IncludeExcelAttachment")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("LookbackDays")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("SendTimeLocal")
                        .HasColumnType("interval");

                    b.Property<string>("ServiceId")
                        .HasColumnType("text");

                    b.Property<string>("Targets")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("TargetsJson")
                        .HasDefaultValueSql("'[]'");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TicketType")
                        .HasColumnType("integer");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("WeeklyDay")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Frequency", "IsActive");

                    b.HasIndex("TenantId", "IsActive");

                    b.ToTable("SlaReportSubscriptions", (string)null);
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.TenantBranding", b =>
                {
                    b.Property<int>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TenantId"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FooterHtml")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FromName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReplyTo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("TenantId");

                    b.ToTable("TenantBrandings");
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.TenantSlaSettings", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("text");

                    b.Property<string>("CalendarId")
                        .HasColumnType("text");

                    b.Property<bool>("UseBusinessHours")
                        .HasColumnType("boolean");

                    b.HasKey("TenantId");

                    b.HasIndex("CalendarId");

                    b.ToTable("TenantSlaSettings", (string)null);
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.Ticket", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AiUnderstanding")
                        .HasColumnType("text");

                    b.Property<string>("AssignedToId")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Attachments")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("CcRecipients")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("CcRecipientsJson")
                        .HasDefaultValueSql("'[]'");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CustomerId")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastReplierName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastViewedByCustomerAt")
                        .HasColumnType("timestamp without time zone");

                    b.PrimitiveCollection<List<string>>("LinkedAssetIds")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("OrganizationId")
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("Replies")
                        .HasColumnType("integer");

                    b.Property<string>("RequesterEmail")
                        .HasColumnType("text");

                    b.Property<string>("ServiceId")
                        .HasColumnType("text");

                    b.Property<string>("SlaPolicyId")
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<double>("TimeSpentHours")
                        .HasColumnType("double precision");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrackingId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("State");

                    b.HasIndex("OrganizationId", "ClosedAt");

                    b.ToTable("Tickets");

                    b.HasDiscriminator().HasValue("Ticket");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.TicketAiSuggestions", b =>
                {
                    b.Property<string>("TicketId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ItemsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TicketId");

                    b.ToTable("TicketAiSuggestions");
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.TicketCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.HasIndex("Name", "Type", "TenantId")
                        .IsUnique();

                    b.HasIndex("Type", "TenantId", "SortOrder");

                    b.ToTable("TicketCategories", (string)null);
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.TicketEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TicketId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TicketEvents");
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.TicketKnowledgeSuggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("KnowledgeBaseArticleId")
                        .HasColumnType("uuid");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.Property<string>("TicketId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KnowledgeBaseArticleId");

                    b.ToTable("TicketKnowledgeSuggestions", (string)null);
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.TicketSlaEscalationEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<string>("MessageId")
                        .HasColumnType("text");

                    b.Property<int>("Metric")
                        .HasColumnType("integer");

                    b.Property<string>("PolicyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecipientsCsv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SendStatus")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TicketId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TriggerPercent")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TicketId", "Metric", "TriggerPercent")
                        .IsUnique();

                    b.ToTable("TicketSlaEscalationEvents");
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.TicketSlaState", b =>
                {
                    b.Property<string>("TicketId")
                        .HasColumnType("text");

                    b.Property<TimeSpan>("AccumulatedPauseDuration")
                        .HasColumnType("interval");

                    b.Property<long>("AccumulatedPauseWorkingSeconds")
                        .HasColumnType("bigint");

                    b.Property<string>("CalendarId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("CompletedWithinResolutionSla")
                        .HasColumnType("boolean");

                    b.Property<bool>("CompletedWithinResponseSla")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBusinessHours")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastResumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PauseReason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("PausedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PausedByUserId")
                        .HasColumnType("text");

                    b.Property<bool>("ResolutionBreached")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("ResolutionDueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ResponseBreached")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("ResponseDueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ResumeAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("TicketId");

                    b.HasIndex("CalendarId");

                    b.HasIndex("ResolutionDueAt");

                    b.HasIndex("ResumeAt");

                    b.HasIndex("Status");

                    b.HasIndex("Status", "CompletedAt");

                    b.ToTable("TicketSlaStates");
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.TicketTimelineEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedByUserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailRecipient")
                        .HasColumnType("text");

                    b.Property<int?>("EmailStatus")
                        .HasColumnType("integer");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastRetryUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MessageHtml")
                        .HasColumnType("text");

                    b.Property<string>("MessageText")
                        .HasColumnType("text");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("RetryError")
                        .HasColumnType("text");

                    b.Property<string>("TicketId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TicketTimelineEvents");
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HashedPassword")
                        .HasColumnType("text");

                    b.Property<bool>("IsTestUser")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrganizationId")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.WorkLog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<double>("Hours")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("NotesHtml")
                        .HasColumnType("text");

                    b.Property<string>("NotesText")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SeenByCustomerAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TechnicianId")
                        .HasColumnType("text");

                    b.Property<string>("TicketId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WorkLogs");
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.WorkingCalendar", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Exceptions")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("ExceptionsJson")
                        .HasDefaultValueSql("'[]'");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ScopeType")
                        .HasColumnType("integer");

                    b.Property<string>("TenantId")
                        .HasColumnType("text");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WeeklyRules")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("WeeklyRulesJson")
                        .HasDefaultValueSql("'[]'");

                    b.HasKey("Id");

                    b.HasIndex("ScopeType", "IsActive");

                    b.HasIndex("TenantId", "IsActive");

                    b.ToTable("WorkingCalendars", (string)null);
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.Change", b =>
                {
                    b.HasBaseType("Helpdesk.Shared.Models.Ticket");

                    b.Property<string>("ChangeType")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Change");
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.Incident", b =>
                {
                    b.HasBaseType("Helpdesk.Shared.Models.Ticket");

                    b.Property<string>("EmailFrom")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("EmailReceivedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Impact")
                        .HasColumnType("text");

                    b.Property<string>("OriginalEmailHtml")
                        .HasColumnType("text");

                    b.Property<string>("OriginalEmailText")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Incident");
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.Request", b =>
                {
                    b.HasBaseType("Helpdesk.Shared.Models.Ticket");

                    b.Property<string>("LegacyCategory")
                        .HasColumnType("text")
                        .HasColumnName("Category");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("text");

                    b.Property<string>("RequestFormId")
                        .HasColumnType("text");

                    b.Property<string>("WorkflowBlockReason")
                        .HasColumnType("text");

                    b.Property<string>("WorkflowStatus")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("WorkflowUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasDiscriminator().HasValue("Request");
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.RequestTask", b =>
                {
                    b.HasBaseType("Helpdesk.Shared.Models.Ticket");

                    b.Property<string>("AutomationBindingId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ConditionExpression")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DueAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EscalateAfterMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("Escalated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("EscalatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EscalationRole")
                        .HasColumnType("text");

                    b.Property<string>("EscalationUserId")
                        .HasColumnType("text");

                    b.Property<string>("FailurePolicy")
                        .HasColumnType("text");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<bool>("IsBlocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsCritical")
                        .HasColumnType("boolean");

                    b.Property<string>("LastAutomationStatus")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastAutomationUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MaxRetries")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrchestratorExecutionId")
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResultJson")
                        .HasColumnType("text");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int?>("RetryDelayMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("SlaBreached")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("SlaStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("OrchestrationExternalRequestId")
                        .HasColumnType("text");

                    b.Property<string>("OrchestrationExternalRunId")
                        .HasColumnType("text");

                    b.Property<string>("OrchestrationJobDefinitionId")
                        .HasColumnType("text");

                    b.Property<string>("OrchestrationRequestDefinitionId")
                        .HasColumnType("text");

                    b.Property<int?>("TaskSlaMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UnblockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasIndex("RequestId");

                    b.HasIndex("Status");

                    b.HasIndex("Escalated", "Status");

                    b.HasIndex("RequestId", "IsBlocked");

                    b.HasIndex("Status", "DueAt");

                    b.HasIndex("Status", "NextRetryAt");

                    b.HasDiscriminator().HasValue("RequestTask");
                });

            modelBuilder.Entity("Helpdesk.Infrastructure.Persistence.Entities.NotificationReadEntity", b =>
                {
                    b.HasOne("Helpdesk.Infrastructure.Persistence.Entities.NotificationEntity", "Notification")
                        .WithMany("Reads")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.AiModel", b =>
                {
                    b.HasOne("Helpdesk.Shared.Models.AiProvider", "Provider")
                        .WithMany("Models")
                        .HasForeignKey("AiProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.ChangeCategoryLink", b =>
                {
                    b.HasOne("Helpdesk.Shared.Models.Change", "Change")
                        .WithMany("CategoryLinks")
                        .HasForeignKey("ChangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Helpdesk.Shared.Models.TicketCategory", "TicketCategory")
                        .WithMany()
                        .HasForeignKey("TicketCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Change");

                    b.Navigation("TicketCategory");
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.EmailTemplate", b =>
                {
                    b.HasOne("Helpdesk.Shared.Models.EmailLayout", null)
                        .WithMany()
                        .HasForeignKey("LayoutId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.IncidentCategoryLink", b =>
                {
                    b.HasOne("Helpdesk.Shared.Models.Incident", "Incident")
                        .WithMany("CategoryLinks")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Helpdesk.Shared.Models.TicketCategory", "TicketCategory")
                        .WithMany()
                        .HasForeignKey("TicketCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incident");

                    b.Navigation("TicketCategory");
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.KnowledgeEmbedding", b =>
                {
                    b.HasOne("Helpdesk.Shared.Models.KnowledgeBaseArticle", "Article")
                        .WithMany("Embeddings")
                        .HasForeignKey("KnowledgeBaseArticleId");

                    b.Navigation("Article");
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.RequestCategoryLink", b =>
                {
                    b.HasOne("Helpdesk.Shared.Models.Request", "Request")
                        .WithMany("CategoryLinks")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Helpdesk.Shared.Models.TicketCategory", "TicketCategory")
                        .WithMany()
                        .HasForeignKey("TicketCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");

                    b.Navigation("TicketCategory");
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.SlaEscalationRule", b =>
                {
                    b.HasOne("Helpdesk.Shared.Models.SlaPolicy", null)
                        .WithMany("Escalations")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.SlaReportSendEvent", b =>
                {
                    b.HasOne("Helpdesk.Shared.Models.SlaReportSubscription", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.TicketAiSuggestions", b =>
                {
                    b.HasOne("Helpdesk.Shared.Models.Ticket", null)
                        .WithOne()
                        .HasForeignKey("Helpdesk.Shared.Models.TicketAiSuggestions", "TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.TicketCategory", b =>
                {
                    b.HasOne("Helpdesk.Shared.Models.TicketCategory", null)
                        .WithMany()
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.TicketKnowledgeSuggestion", b =>
                {
                    b.HasOne("Helpdesk.Shared.Models.KnowledgeBaseArticle", "Article")
                        .WithMany()
                        .HasForeignKey("KnowledgeBaseArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.TicketSlaEscalationEvent", b =>
                {
                    b.HasOne("Helpdesk.Shared.Models.Ticket", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.TicketSlaState", b =>
                {
                    b.HasOne("Helpdesk.Shared.Models.Ticket", null)
                        .WithOne()
                        .HasForeignKey("Helpdesk.Shared.Models.TicketSlaState", "TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.RequestTask", b =>
                {
                    b.HasOne("Helpdesk.Shared.Models.Request", "Request")
                        .WithMany("Tasks")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("Helpdesk.Infrastructure.Persistence.Entities.NotificationEntity", b =>
                {
                    b.Navigation("Reads");
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.AiProvider", b =>
                {
                    b.Navigation("Models");
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.KnowledgeBaseArticle", b =>
                {
                    b.Navigation("Embeddings");
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.SlaPolicy", b =>
                {
                    b.Navigation("Escalations");
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.Change", b =>
                {
                    b.Navigation("CategoryLinks");
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.Incident", b =>
                {
                    b.Navigation("CategoryLinks");
                });

            modelBuilder.Entity("Helpdesk.Shared.Models.Request", b =>
                {
                    b.Navigation("CategoryLinks");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
