<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);CS0618;CS8602;CS8604</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.21.0" />
    <PackageReference Include="Dodo.Primitives" Version="5.0.0" />
    <PackageReference Include="HtmlAgilityPack" Version="1.13.0" />
    <PackageReference Include="HtmlSanitizer" Version="9.2.1039" />
    <PackageReference Include="MailKit" Version="4.18.0" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.Abstractions" Version="10.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.13" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.12" />
	  <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.12" />
	  <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="10.10.0" />
    <PackageReference Include="Microsoft.Kiota.Abstractions" Version="2.1.2" />
    <PackageReference Include="Microsoft.Graph" Version="6.7.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.12" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Helpdesk.Application\Helpdesk.Application.csproj" />
    <ProjectReference Include="..\Helpdesk.Shared\Helpdesk.Shared.csproj" />
  </ItemGroup>

</Project>
